services:
  profit-postgres:
    image: postgres
    container_name: profit-postgres
    environment:
      POSTGRES_USER: profit
      POSTGRES_PASSWORD: profit
      POSTGRES_DB: profit
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U profit"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - database
  profit-data-import:
    container_name: profit-data-import
    build:
      context: data_import
      dockerfile: Dockerfile
    environment:
      DB_HOST: "profit-postgres"
    depends_on:
      profit-postgres:
        condition: service_healthy
    networks:
      - database
  profit-api:
    container_name: profit-api
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      DB_HOST: "profit-postgres"
    ports:
      - "8080:8080"
    depends_on:
      profit-postgres:
        condition: service_healthy
    networks:
      - database
      - web
  profit-front:
    container_name: profit-front
    build:
      context: front
      dockerfile: Dockerfile
    environment:
      - BASE_URL=http://profit-api:8080
    ports:
      - "80:80"
    networks:
      - web
networks:
  database:
  web:
